id: P14912120
initial_creation_type: input
source_metadata:
  title: Rinchen Terdzö Series
  language: en
  description: 'Texts belonging to (and related to) the Rinchen Terdzö (rin chen gter
    mdzod) or Precious Treasury of Revelations, one of the five treasuries of Jamgön
    Kongtrul Lodrö Thayé (1813–1899). Note that the volume numbers below correspond
    to the Shechen Publications edition (2007–2008):'
  volume:
    6039e6eaad79480f8fb5eb8838bf33dd:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Volume 1
    a6546b2f204b446194ffaca6c16c2b47:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Volume 1
    9e5c6be294af4e60ae3e1608371e5086:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Volume 1
    589cdf5981884102b12b6d1bed2e4990:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Volume 1
    a67169503008476bbff9426c809bcaaa:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Volume 1
    b82a89dd48374e3c8459e0e342afb92a:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Volume 1
    34f70dfc821b4127a14ed6492413e027:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Volume 1
    ac9777e89fb74dd0aefa69e806fd7fc9:
      title: 'Three Reasons for Confidence: A Work Telling the Life and Liberation
        Story of the Great Master Padmākara'
      parent: Volume 1
    6802693f56c6465789d851076f4cd772:
      title: The Lament of Rudra
      parent: Volume 5
    eac1fb8f0ff3488883dab6ffacbaab77:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Volume 5
    56a96789344e436888624dcaf5505f94:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Volume 5
    801f4891bd5f49d4ad8d1e42ef7ee624:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Volume 5
    c61409d6f9e44590a454c8a3eb9af347:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Volume 5
    c6e67b0471ba4525b74157aa7ce09073:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Volume 5
    f9cafa2dbc254d4d9ffb2f2fd5bf497f:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Volume 5
    616ab57a8df14afaa5c741dc598646cb:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Volume 5
    cccbd62be2d143919281d436f387fbe3:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Volume 6
    8c02a28c448b4f298c51015f0a23c93a:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Volume 10
    f91ee04e1e584ec3a48507d3961d1386:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Volume 10
    7cb6ec31f2154ef883785e7fdc554a7e:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      parent: Volume 10
    56c79153ffcb4c4382e1969d4657fa8b:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Volume 10
    f9066922952344dbbd2a28409381c2cd:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Volume 10
    efb73de1db42439383231627c567b0a9:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Volume 10
    a8b8368ddd714600a209b6955f9c0eb5:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Volume 10
    0becd3aedd254055bfda02f765d84a92:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Volume 11
    0394aa6f6eab4b65a55e75e4af33316f:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Volume 11
    af4ff9bc1389409c9f7a5f87591d0e4d:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Volume 11
    5342d4a4588044bda15711a4caddac19:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Volume 11
    61f947bab4ab41a49e15ed232f9f56ac:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Volume 16
    c4b108240969413d88525b387f8e9288:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Volume 16
    447f186bf2b04bc2b649e67e8f9c5b40:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Volume 21
    dc65e2ac280f44a8ab30281ae23b31ad:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Volume 22
    7b12c5250f55442a9a56e6221c425386:
      title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural
        Transmission
      parent: Volume 26
    17757e727f6949efbb0493ad188b36f6:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Volume 31
    db1dbe7f7dac4d9f9cbbed00f57b02f9:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: Volume 32
    81ff0f7c37014ba2a83b48f3bbde8e0b:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Volume 36
    e1c49c14fc194c0aad9d1ec8a40082a9:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Volume 36
    cc62619be0154f5e9fc9de4964321071:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Volume 36
    a67c5f3ec03f424681570bbfa28ea920:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Volume 36
    d3f3f37fecf2472dbb27ac96ba78a360:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      parent: Volume 36
    09dca1fb810d449dbc28b976ed6f1567:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Volume 36
    9ffb5f1f344e438c9815ca14b8656374:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Volume 36
    2105159bc6f44ac39cd3f85de2f5a8a4:
      title: The Twenty-Eight Commitments
      parent: Volume 41
    224d05e9cf3746aab2ab7b1c80c02ab9:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Volume 41
    dad33ddc3e5345d4b0bd5be091ee4d11:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Volume 41
    61f9b8390b43422f8ab189df62c5ec04:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Volume 41
    9349ca14573341f99f6f57049e2a79dc:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Volume 41
    2a18f6ad228a423f8e5e1d457980b2e0:
      title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
        of Enlightened Body, Speech and Mind'
      parent: Volume 41
    9cabd526eb954e3fa943ece435718ac3:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: Volume 41
    3066b5ee158e4b4283a4310df02ec074:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Volume 42
    7a9bbbdd78c9427c89b70a148ef1e4ec:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Volume 42
    6206806dc97342f3b7f4ecf505b26d5e:
      title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
      parent: Volume 42
    12ef1a5d52964b0d9fc5e1f2f92a7595:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Volume 43
    9fb89f07bfea4f08a86e1cf19ce12734:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Volume 43
    cb7b85bd38de471ea3459b3d556dca31:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Volume 45
    d770a6929bc84222a8465b9ca78dbd2f:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Volume 47
    cad3fd926cf84a84915d06f7f1ab73d7:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Volume 48
    57cf99bfb5614c7fb5e78d3fb24d329f:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Volume 48
    fa0a64a13c8c435c9eb0cdb3eb508c0f:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Volume 48
    19c7fcf6b9964f79b4a0a9d69c461f26:
      title: 'Opening the Door to Great Bliss: An Aspiration Towards the Realm of
        Abhirati'
      parent: Volume 48
    7d5769e708da473b92ce1dcff91cd1c1:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Volume 49
    cb4a0a6b8a3a4e15bd21e7c927c4f609:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Volume 49
    441ed85f78224e18ae7c4825ef26fb40:
      title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
        White and Red Amitāyus'
      parent: Volume 49
    c6614253438b46c8a7109b50b1511bc6:
      title: Prayer for the Future of the Dharma
      parent: Volume 52
    07328b13f3a2433fa2db9a8e11a63808:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Volume 52
    fba6a2dc8db44278a6a1a419d6b7dfbf:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Volume 52
    19154bb66e924324b1c1f10c5d12b4eb:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Volume 52
    240e828a65e34d27b85c395f0cf7c6e0:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Volume 60
    290f039f38894ab994645f5e8906d024:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Volume 60
    3ae55985b5bc4ae3bb46ad349cdb6644:
      title: The Pointing-the-Staff Instruction
      parent: Volume 60
    7b4e7b46b7564aeb8f371fb26e273dc6:
      title: Yeshe Tsogyal's Prayer
      parent: Volume 60
    f74241b9df5a44889d5716a6a5e80634:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Volume 60
    fbd1c626bb394feba777383d2ba61ff0:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Volume 65
    7347010a9edf4f26b4cc35bb99938866:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Volume 67
created_at: '2022-03-01T05:31:39.686804'
last_modified_at: '2022-03-01T05:31:39.686811'
